-- 코드를 입력하세요
# 2022년 8월 ~ 2022년 10월까지 총 대여 횟수가 5회 이상
# 월별 자동차 ID 총 대여횟수 AS RECORDS
# 대여횟수가 0인 경우 제외
#  ORDER BY START_DATE, CAR_ID DESC
SELECT MONTH(START_DATE) as MONTH, CAR_ID, COUNT(1) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
where START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
AND car_id in (select car_id from CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
                     GROUP BY CAR_ID
                     HAVING COUNT(1)>= 5)
GROUP BY MONTH(START_DATE),CAR_ID
ORDER BY MONTH, car_id desc

